### PR TITLE
Translation fixes and additions

### PR DESCRIPTION
**Pull request by gigan3rd**
Edited german translation
Added russian translation

### CODE REVIEW

**Comment by petmue** [comment]
Your german translation looks good to me, except that you are not completely consistent
> <string name="dialog_restore_failed">Um die Notizen wiederherzustellen, muss die Backup Datei ...

should be

> <string name="dialog_restore_failed">Um die Notizen wiederherzustellen, muss die Sicherungsdatei ...

**Comment by gigan3rd** [comment]
Oh, I oversaw that one. Will fix it right away.

**Comment by petmue** [comment]
> Oh, I oversaw that one. Will fix it right away.
You mean you overlooked it. ;-)

**Comment by gigan3rd** [comment]
Fixed as well :P

**Comment by gigan3rd** [comment]
Pull request closed. I managed to fix issue #28 in the meantime, the translation fixes are already in there. (https://github.com/adrianchifor/Swiftnotes/pull/30)

**Pull request closed without merging**
