### PR TITLE
Small improvement of README

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RyDroid** [comment]
Why did you reject this pull request?
Regards.

**Comment by berryman13** [comment]
It was rejected because of the URL formatting. Looks to be formatted for reddit, and you removed it all.

**Comment by RyDroid** [comment]
You do not understand how I change URL formatting in a Reddit way (I do not use this website service).

**Comment by adrianchifor** [comment]
It's rejected because the current README.md looks different and the formatting in your pull request is based on your personal preference. Also, if I merge now, it will ruin the current formatting. Locked.

**Pull request closed without merging**
